### ISSUE TITLE
Cmake buid broken due to unknown test_source

### ISSUE THREAD

**Issue by fouriaux** [ornladios/ADIOS#130]
At Cmake configuration, from official release http://users.nccs.gov/~pnorbert/adios-1.11.0.tar.gz
-- Configuring done
CMake Error at tests/test_src/CMakeLists.txt:31 (add_executable):
  Cannot find source file:
    read_points_3d.c

This is due to the fact that no file read_points_3d.c does not exist in tests/test_src
A work around that work is to modify the CMakeLists.txt in tests/tests_src to remove this particular test.

**Comment by pnorbert** [comment]
Thank you for reporting this bug. The file is missing from the distribution. We fixed the cmake build in the master branch today. Would you be willing to try to build the master branch with cmake and report if you have any issues with it? It now builds the whole test suite in addition for the fix.

**Comment by fouriaux** [comment]
​Thanks a lot !

Sure, I can try to build it on my morning :-)

Have a great day,

Jeremy

________________________________

**Comment by fouriaux** [comment]
I have compiled from master branch using Cmake, everything is working now :-) 
thanks !
