### ISSUE TITLE
adios_read_open_file seems to stall when not finding file

### ISSUE THREAD

**Issue by fouriaux** [ornladios/ADIOS#131]
adios_read_open_file seems to stall when not finding file
===
I try to do a restart feature in my program: I want to check if a file success to open for reading variables and continue if not. However my program seems to block completely after adios_read_open_file fail (which should return NULL and continue).

I run my execution via this command line:
```
srun -n4 frozen_read 
```

If I run my program without srun, it is behaving properly: the adios_read_open_file call return NULL as expected. Please find below my code...

[frozen_read.cc.txt](https://github.com/ornladios/ADIOS/files/1036185/frozen_read.cc.txt)
[config.xml.txt](https://github.com/ornladios/ADIOS/files/1036186/config.xml.txt)
[CMakeLists.txt](https://github.com/ornladios/ADIOS/files/1036179/CMakeLists.txt)

**Comment by pnorbert** [comment]
Uhh, I may have introduced a new bug. I will test this when I am back from
the holiday weekend.

**Comment by fouriaux** [comment]
​Hi,

I will try to have a quick look in the code :-)


Kind regards,

Jeremy.


________________________________

**Comment by fouriaux** [comment]
ok :-)
I forgot to mention about the error message that is returned:
```
ERROR: MPI open failed for not_existing.bp: 'File does not exist, error stack:
ADIOI_UFS_OPEN(69): File not_existing.bp does not exist'
ERROR: File open failed: not_existing.bp
```

**Comment by fouriaux** [comment]
This proble does appears only with adios_read_open_file: adios_read_open function have correct behavior.

**Comment by pnorbert** [comment]
Fixed this bug. Can you give it a try? Thanks.

**Comment by fouriaux** [comment]
Thanks ! It is working :+1:  
However I got some remaining error messages when I disable Verbosity of the method:
> srun -n4 ./1_frozen_read 
Invalid error code (269009701) (error ring index 1 invalid)
Invalid error code (269009701) (error ring index 1 invalid)
Invalid error code (269009701) (error ring index 1 invalid)
Invalid error code (269009701) (error ring index 1 invalid)
Invalid error code (269009701) (error ring index 1 invalid)
Invalid error code (269009701) (error ring index 1 invalid)

I am not sure if it is related..

**Comment by pnorbert** [comment]
I cannot reproduce this message. You meant setting "verbose=0" in adios_read_init_method(), right? My run is quiet in that case.

**Comment by fouriaux** [comment]
yes for setting verbose=0.
Ok, so it is probably something with my configuration, I will create a new ticket if I don't find something on that.
Thanks a lot.
