### ISSUE TITLE
calling adios_set_max_buffer_size with different values leads to different final file sizes ?

### ISSUE THREAD

**Issue by fouriaux** [ornladios/ADIOS#136]
Using no-XML API, setting adios_set_max_buffer_size with different values leads to different sizes of final file. 
This behavior appears when using adios_write_byid on a variable declared several times to access several offsets by same rank. When adios_write_byid is called only one time per variable name declared, we have identical final file size whatever adios_set_max_buffer_size we set.

This was tested on x86 machine with Intel Compiler, using Master branch from June 5, 49b720f76ab9097392fdadfeda0f13067dc9e800

[max_buffer_size.zip](https://github.com/ornladios/ADIOS/files/1122477/max_buffer_size.zip)

**Comment by pnorbert** [comment]
I cannot recreate the issue on my VM with gnu compiler, with either the master HEAD or 49b720f, with either single process or 4 process runs. 
How did you run the tests?

**Comment by fouriaux** [comment]
using `srun -n 4` on each executable  I got the following output files:
 > du -h *.dat
64K	10_write_max_buffer_1M.dat
1.0M	10_write_max_buffer_4M.dat
1.0M	1_write_max_buffer_1M.dat
1.0M	1_write_max_buffer_4M.dat

>[fouriaux@bbpviz1 build]$ $ADIOS_ROOT/bin/bpls 10_write_max_buffer_1M.dat
  integer  global_size  scalar
  integer  batch_size   scalar
  integer  offset       scalar
  byte     data         {40960}
[fouriaux@bbpviz1 build]$ $ADIOS_ROOT/bin/bpls 10_write_max_buffer_4M.dat
  integer  global_size  scalar
  integer  batch_size   scalar
  integer  offset       scalar
  byte     data         {40960}

**Comment by pnorbert** [comment]
Can you please attach the 'bpdump' output for each file. I found no
difference between the two in my runs.

**Comment by fouriaux** [comment]
actually I have recompiled everything, and I cannot reproduce this problem anymore. I will check what difference could have happened between those runs at our system side.

Thanks !
