### ISSUE TITLE
writting uint64_t and size_t on BGQ machine

### ISSUE THREAD

**Issue by fouriaux** [ornladios/ADIOS#137]
I have experienced a discrepancy in the behavior of ADIOS on BGQ machine compared to x86:
I try to transfer some data using the no-xml API. 
I delcare my variables as follow: 
```
adios_define_var          ( adios_group_id, "global_size",  "", adios_integer, "", "", "");
```
and I am writting this way:
```
adios_write (adios_handle, "global_size", (void*) &total_size);
```

I initially declared total_size as uint64_t and tested as well with size_t, this provide correct behavior on x86, but incorrect results on BGQ. replacing the delcaration with int make it functional on BGQ.

**Comment by pnorbert** [comment]
Please note that adios_integer is 4 bytes long. uint64_t and size_t are
both 8 bytes long. You need to define your output variable with adios_long
type to store such variables correctly. With adios_integer and storing 4
bytes, you are lucky to store the relevant bytes on a little endian
machine, so it seems to work.

**Comment by fouriaux** [comment]
sorry my mistake, it make all sense now.
