### ISSUE TITLE
there is no configure file in the master version

### ISSUE THREAD

**Issue by lwh1990** [ornladios/ADIOS#144]
Hi, all
I am a new user to ADIOS. I cannot figure out how to install when there is no configure file in the master version.
Thanks.

**Comment by pnorbert** [comment]
Hi,
Is there any reason you don't just download the 1.12 version from
http://users.nccs.gov/~pnorbert/adios-1.12.0.tar.gz?
That has the configure file. We don't store the autogenerated files in the
git repository. You need to run ./autogen.sh first to generate them if you
use the master branch. Then runconf has a lot of examples on how to build
it on various machines.

**Comment by lwh1990** [comment]
Thanks. I have download 1.12.0 version and it occur many "conflicting types for 'MPI_XXX' " compiling error when I make it. How to fix that?

**Comment by pnorbert** [comment]
You probably have to specify the compiler sets, separately for the
sequential build and for the parallel build. ADIOS builds both at once.

    export MPICC=mpicc
    export MPICXX=mpicxx
    export MPIFC=mpif90
    export CC=gcc
    export CXX=g++
    export FC=gfortran

**Comment by lwh1990** [comment]
Thanks. I have successfully installed it.
