### ISSUE TITLE
local arrays are not handled consistently in DATASPACES method

### ISSUE THREAD

**Issue by burlen** [ornladios/ADIOS#148]
when using the MPI(write), BP(read) when I define local arrays I can give only the path to where the local array length is stored and give "" (empty strings) for global length and offset arguments. For example:
```
adios_define_var(gh, data_path.c_str(), "", adios_tt<n_t>::type(),
    elem_path.c_str(), "", "");
```
However, when I run this code with dataspaces, dataspaces errors out with the following message
```
'obj_put_update_dht()': this should not happen, num_de == 0 ?!
```

I can work around this by the following change, give the gloabl length and offsets:
```
adios_define_var(gh, data_path.c_str(), "", adios_tt<n_t>::type(),
    elem_path.c_str(), elem_path.c_str(), "0");
```
Having to do this contradicts the documentation, and is inconsistent with MPI method, but works for all methods I've tried.

code to reproduce is [here](https://drive.google.com/open?id=0B3y5yyus32lvdlNuN3czbk5WaTQ)
`make issue_148`

**Comment by burlen** [comment]
@mw70 issue 1

**Comment by pnorbert** [comment]
Hi. Staging methods only support global arrays. They never worked with
local arrays.

**Comment by burlen** [comment]
Ahh, I see. I thought that all the methods would work the same to swap 
out the back end seamlessly. I misunderstood. Work around is easy enough.

**Comment by pnorbert** [comment]
That was always the goal, except for local arrays. You are not the first
complaining about it.
