### ISSUE TITLE
flexpath parallel issue

### ISSUE THREAD

**Issue by burlen** [ornladios/ADIOS#149]
the code to reproduce is [here](https://drive.google.com/open?id=0B3y5yyus32lvdlNuN3czbk5WaTQ)

```
make issue_146
```

write side
```
$mpiexec -np 2 ./put test.bp FLEXPATH 10 2
```

read side
```
$mpiexec -np 2 ./get test.bp FLEXPATH
```

errors reported by read side.
```
returning unknown for: ffs_type: char [Z__dataset_b0_Parray_b1_Pnumber_bof_belements]
returning unknown for: ffs_type: char [Z__dataset_b1_Parray_b1_Pnumber_bof_belements]
ERROR: file not opened correctly.  var does not match format.
ERROR: file not opened correctly.  var does not match format.
```

**Comment by eisenhauer** [comment]
Flexpath changes have been pushed.  The example doesn't quite work yet because it uses local arrays rather than global, but I have sent modified code for that.
