### ISSUE TITLE
1.13.1: --enable-shared ignored?

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#185]
Is it possible that `configure --enable-shared` does not produce shared libraries in `ADIOS 1.13.1`?

Trying to build them on Debian 9.4 with GCC 6.4 and only get `.a` archives.

**Comment by ax3l** [comment]
@pnorbert did anyone take a look at this? This is a bit of a pitty for many system with the 1.13.1 release :)

**Comment by pnorbert** [comment]
I don't think we ever had shared build. We could never figure out how to
build them and still be able to build static libraries on all kinds of
machines. Both the Makefile.am and CMakeLists.txt are written to build .a
static libraries and has no option to build shared.

**Comment by ax3l** [comment]
Really? I think to remember we had shared libs before the last release. Did I just not realize before? Huh!
