### ISSUE TITLE
ADIOS_READ_METHOD_BP_AGGREGATE not working in read API

### ISSUE THREAD

**Issue by khou2020** [ornladios/ADIOS#194]
Hi:

I got the following error using ADIOS_READ_METHOD_BP_AGGREGATE method in ADIOS read API. It happens when I try to schedule read with a bounding box selection.

core/common_read.c:3663: common_read_schedule_read_byid: Assertion `raw_varinfo && transinfo' failed.
Aborted (core dumped)

To verify the issue, I modified the read_all example to use ADIOS_READ_METHOD_BP_AGGREGATE.
I add MPI_Init and MPI_Finalize at beginning and end of the program. The compiler is swapped with mpicc. -DNOMPI is removed. It is linked to the mpi version of ADIOS. I pass MPI_COMM_WORLD to adios_read_open_file. I let it read the arrays.bp file generated by the arrays_write.c example program. I got the error at adios_schedule_read_byid.
Number of aggregator and chunk size both set to 1 via environment variable (setenv).

**Comment by pnorbert** [comment]
Adios only supports the plain BP reading (every process reads). The
aggregate reading routines were never completed. They should not be in the
public release. Sorry for the confusion.
