### ISSUE TITLE
Unnecessary files in $(bindir)

### ISSUE THREAD

**Issue by QuLogic** [ornladios/ADIOS#33]
After `make install`, the following files exist in `$(bindir)` that don't really belong there. They are not executable, or don't actually run:
- `ad_config.py` - Doesn't do anything by itself. Python files should be put in `site-packages`. Automake has [direct support for Python](http://www.gnu.org/software/automake/manual/html_node/Python.html), so you can easily find where that is with `pythondir`.
- `adios_config.flag` - Not executable, and does nothing if sourced. This one could possibly be okay if it `export`ed its variables. Then it could be `source`d.
- `git.status` - Not executable, and the name is wayy too generic.
- `list_methods`, `list_methods_nompi`, `list_methods_readonly`, `list_methods_readonly_nompi`, `set_method.sh` - I don't actually think there's anything wrong with them per se; they just have slightly generic names.
- `type_mapper.py` - Again, this doesn't do anything. It should be put in `site-packages`.

**Comment by pnorbert** [comment]
Finally removed all files from bin/ that don't belong there.
[commit 6180fa5](https://github.com/ornladios/ADIOS/commit/6180fa5a5fe41eae9b8e0b140530ab9739b105e0)
