### ISSUE TITLE
Python files are installed to incorrect directory

### ISSUE THREAD

**Issue by QuLogic** [ornladios/ADIOS#35]
Python files are [hard-coded](../blob/master/utils/skel/Makefile.am#L5) to install to `$(libdir)/python`. On most distros, Python files have been versioned, so that the correct directory is (at least) `python2.7` or `python3.3`, etc.

Fortunately, automake has [support for Python](http://www.gnu.org/software/automake/manual/html_node/Python.html), so it's just a matter of using the builtin machinery and things will be in the right place.

**Comment by yyalli** [comment]
Sorry. I haven't checked this issue for a long time. As of 1.9.0, I think this problem is fixed by using pip and Makefile. Please let us know if you still have this issue.
