### ISSUE TITLE
float indices in Python bindings

### ISSUE THREAD

**Issue by rmchurch** [ornladios/ADIOS#53]
I would recommend supporting floats for indexing with the Python Adios bindings, similar to the h5py package for HDF5 files in Python. See below.

In h5py, the following works:
In [25]: file_path5='file.h5'
In [26]: f5 = h5py.File(file_path5)
In [27]: d1 = f5[data_path][:,1,:]
In [28]: d2 = f5[data_path][:,1.,:]

In adios, we get an error when using a float to slice:
In [29]: file_path=''file.bp'
In [30]: f = ad.file(file_path)
In [31]: d1 = f[data_path][:,1,:]   
In [32]: d2 = f[data_path][:,1.,:]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-a670ea0b6f0c> in <module>()
----> 1 d2 = f[data_path][:,1.,:]

adios.pyx in adios.var.__getitem__ (adios.cpp:14190)()

AttributeError: 'float' object has no attribute 'step'

**Comment by ax3l** [comment]
It would also be great if we could bring the general interface closer to `h5py` in general.

Some points:
- `.file` -> `.File` (upper case in the read API)
- `.attr` -> `.attrs` renaming
- emulating that each group and each variable object can in turn again have a `.attrs` member (that simply checks the global list of attributes for attributes that share the same prefix)

**Comment by yyalli** [comment]
Just wondering what is the correct way to handle if the index is 1.5. For an example,
f[data_path][:,1.5,:]
Raise an error? Round up to 2? or Cut to 1?

**Comment by yyalli** [comment]
> emulating that each group and each variable object can in turn again have a .attrs member (that simply checks the global list of attributes for attributes that share the same prefix)

Can you give any example? I just need to have a clear picture for this.

**Comment by ax3l** [comment]
@yyalli Of course, I glad to provide one!
```python
import adios as ad

f = ad.file("adios_test.bp")
t = f["temperature"] # type: adios.var

# here t could have a member dictionary attr(s) again
# which looks up all attributes starting with t.name
print( t.attrs["description"] )

# the same should be possible for groups
g = f["someSubGroup/anOtherGroup/"] # type: adios.group
# now match: f.attrs["/someSubGroup/anOtherGroup/anOtherAttribute"]
print( g.attrs["anOtherAttribute" )
```

**Comment by rmchurch** [comment]
@yyalli If the index is 1.5, I think the correct behavior should be cut to 1 (you should just do an int(index) call on any slicing index put into the getitem method. This is what h5py does).

**Comment by ax3l** [comment]
@yyalli did my example help you and is there still effort on making the adios numpy wrapper more h5py like (to introduce objects)?

**Comment by ax3l** [comment]
@yyalli ping :)

**Comment by yyalli** [comment]
Hi, Axel,

Sorry for my late reply.

I partially implemented attaching attrs to variables. Recent examples can
be found in wrapper/numpy/tests/test_adios_attribute.py

However, I haven't implemented the group concept yet. Please try the
example and let me know if this update works for you or not.




On Mon, Dec 14, 2015 at 4:10 AM, Axel Huebl <notifications@github.com>
wrote:

> @yyalli <https://github.com/yyalli> ping :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ornladios/ADIOS/issues/53#issuecomment-164384201>.
>



-- 
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

**Comment by yyalli** [comment]
Michael, Sorry for this late update.

 I am still working on this but planning to finish by the end of this year
:) I will let you know soon.


On Thu, Oct 8, 2015 at 11:39 AM, Michael Churchill <notifications@github.com
> wrote:

> @yyalli <https://github.com/yyalli> If the index is 1.5, I think the
> correct behavior should be cut to 1 (you should just do an int(index) call
> on any slicing index put into the getitem method. This is what h5py does).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ornladios/ADIOS/issues/53#issuecomment-146582400>.
>



-- 
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

**Comment by yyalli** [comment]
Now indexing can take floats and numpy boolean arrays too.
