### ISSUE TITLE
Build on Titan failing

### ISSUE THREAD

**Issue by anshumang** [ornladios/ADIOS#54]
This is the error message -
genarray.F90:185:0: fatal error: gwrite_genarray.fh: No such file or directory
 #include "gwrite_genarray.fh"
 ^
compilation terminated.
copyarray.F90:207:0: fatal error: gread_genarray.fh: No such file or directory
 #include "gread_genarray.fh"
 ^
compilation terminated.
make[3]: *** [genarray-genarray.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [copyarray-copyarray.o] Error 1
make[3]: Leaving directory `/autofs/nccs-svm1_home1/anshuman/ADIOS/tests/genarray'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/autofs/nccs-svm1_home1/anshuman/ADIOS/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/autofs/nccs-svm1_home1/anshuman/ADIOS'
make: *** [all] Error 2

**Comment by anshumang** [comment]
anshuman@titan-ext4:~/ADIOS> cd tests/genarray/
anshuman@titan-ext4:~/ADIOS/tests/genarray> ../../utils/gpp/gpp.py ./genarray3d.xml 
gpp.py failed.

**Comment by pnorbert** [comment]
Hi, we can't build adios on titan with gcc the usual way since the compiler
update. Use the following compiler settings before configuring adios:
        export CC=gcc
        export FC=gfortran
        export CXX=g++
        export MPICC=cc
        export MPIFC=ftn
        export MPICXX=CC

**Comment by anshumang** [comment]
Thanks :+1:
