### ISSUE TITLE
Master: Numpy Wrapper

### ISSUE THREAD

**Issue by psychocoderHPC** [ornladios/ADIOS#55]
Comparing to the latest release, `1.9.0`, the numpy python wrapper seems to be broken in `master` as of f67b888a5786dd82aebbb279d8d1013509e6c38d

I installed adios from both the v1.9.0 tag and `master` and tested the numpy wrapper from pip and `wrapper/numpy` itself.

The result is, that in the latest master
```python
import adios as ad
f = ad.file("someFile.bp")
```

leads to a segmentation fault, killing the whole python instance.

Did something change in the adios library the wrapper interfaces with?
Unfortunately I do not have a python with debug symbols by hand to go further into the issue via gdb.

**Comment by yyalli** [comment]
Adios 1.9.0 release version (or with v1.9.0 tag) should work with pip installation (adios python 1.9.0). However, the most recent python wrapper (which is in wrapper/numpy of the current master branch) will not work with the release version of Adios. There are changes and it will only work with the most recent Adios version. Is this the case that you got the error?

**Comment by ax3l** [comment]
@yyalli yes, we tried to latest `master` for adios itself + the latest master `numpy` wrapper and got the error.

We did expect that `master` HEAD + `1.9.0` pip won't work, but `master` HEAD of *both* was broken at the time of writing.

**Comment by yyalli** [comment]
I have found this error while running unittest on other machine. Do your "somefile.bp" have a string attribute? I haven't found out the details yet. Will dig more and let you know soon.

**Comment by ax3l** [comment]
Thank you, great! :sparkles: 

> Do your "somefile.bp" have a string attribute?

No, in this test we did not use strings in the PIConGPU ADIOS output (but will use soon).

**Comment by ax3l** [comment]
problem solved by now :) @psychocoderHPC can you close?
