### ISSUE TITLE
Memory leaks during read

### ISSUE THREAD

**Issue by sim-saurabh** [ornladios/ADIOS#58]
Allocations by `adios_read_hooks_init` and `adios_query_hooks_init` leak memory. Simple test case (had to append `.txt` for github) and valgrind output attached. Adios 1.9.0, no MPI, valgrind 3.11, 64-bit Linux system.
[adios.c.txt](https://github.com/ornladios/ADIOS/files/93091/adios.c.txt)
[valgrind.txt](https://github.com/ornladios/ADIOS/files/93092/valgrind.txt)

**Comment by pnorbert** [comment]
Hi, thanks for the info. Do you think it matters? One is supposed to
finalize adios at the end of the application just before MPI_Finalize(). So
that adios_finalize() does not free every bit of memory, are there any
circumstances where this may cause trouble?

On Sat, Jan 16, 2016 at 4:28 PM, Saurabh Tendulkar <notifications@github.com

**Comment by sim-saurabh** [comment]
Not much trouble for me, only have to add suppressions for valgrind for our testing. Although it's not my usecase I could see one where adios is run as needed, while the application stays alive, so a separate module handles all adios stuff, so probably not ideal for it to leak memory every time.

**Comment by ax3l** [comment]
Huh, should check if the same leak occurs for
```C++
adios_init_noxml(MPI_Comm);
adios_finalize(rank);
```

... we call that several thousand times.

**Comment by pnorbert** [comment]
The query and read method hooks are not freed in adios_read_finalize. But
they are allocated only once at the first initialization so there is no
memory leak.

The write methods are actually allocated and freed in each
adios_init/adios_finalize steps.

Let me know if you find other types of memory leaks.

**Comment by ax3l** [comment]
all right, thank you!
