### ISSUE TITLE
Numpy: Python3 Support

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#60]
Hi @yyalli,

are you planning to add Python3 support for the numpy wrapper?

Thanks,
Axel

**Comment by yyalli** [comment]
It sounds good to have python3 support. I will start working on this soon but it may take some time.

**Comment by ax3l** [comment]
have you thought about maybe maintaining the wrapper in an independent repo and including the ADIOS C "main" library as a git submodule?
This would allow you to run continuous integration tests, e.g., with https://travis-ci.org that could make development way easier by testing various python and cython versions on the fly.

**Comment by yyalli** [comment]
Just updated to support python3 (as well as python2). Only tested with python 3.5 and 2.7. It may need more tests. Anyway, I will appreciate if you can check and report any problem.

**Comment by ax3l** [comment]
Tested with Debian 8 "Jessie" with Python 2.7 & 3.4 and serial adios.

- install: works
- open file: works
- reading variable via `f["/ion__ExB_shear"][()]` from `utils/bpsplit/test/flow11.bp`
  - ok in Python 2.7
  - segfault in Python 3

@yyalli since GitHub is your mainline, can I *please* get some feedback on continuous integration I proposed? I can even write you the files for [travis-ci](http://travis-ci.org/) and it's free...

**Comment by ax3l** [comment]
update: python 3 works, too. did not run `setup.py clean` before building it after python2 :)
