### ISSUE TITLE
Python/Numpy Module: __version__ Attribute

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#61]
@yyalli first of all thank you for the many and great updates in the last months! :sparkles: 

It would be fantastic if a `adios.__version__` attribute would be supported.
This version represents the version of the **ADIOS Python module**, so currently `1.9.1b6` (not the version of the ADIOS release, currently `1.9.0`, nor the version of ADIOS used to write a specific file).

Defined in [PEP0396](https://www.python.org/dev/peps/pep-0396/) for modules (also briefly mentioned in [PEP8](https://www.python.org/dev/peps/pep-0008/)).

Examples:
```python
import numpy as np
import h5py as h5
import adios

print(np.__version__)
print(h5.__version__)
# print(adios.__version__) # not implemented

# my current work-around
import pkg_resources;
print(pkg_resources.get_distribution('adios').version)
```

**Comment by yyalli** [comment]
Great suggestion. I will work on this soon.

**Comment by yyalli** [comment]
As of 1.9.1b7 release, I have added the version info (__version__).

**Comment by ax3l** [comment]
Thank you very much, that is great! :sparkles:
