### ISSUE TITLE
Python: A few More basic ndarray Attributes on Variables

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#70]
Dear @yyalli ,

can we add a few more, very basic `numpy.ndarray` attributes to the `variables` in the python binding?

I am especially looking for:
- [`shape`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape), making `dims` just an alias of it
- [`size`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html#numpy.ndarray.size).

[Here is how h5py](https://github.com/h5py/h5py/blob/master/docs/high/dataset.rst) handles its `variables` (called "datasets" in their speak).

(This is a convenience request making the binding close to `numpy` and `h5py` to make porting scripts easier.)

**Comment by yyalli** [comment]
Done with adding two attributes: shape and size.

**Comment by ax3l** [comment]
thank you very much! :sparkles: 

(Commit: 3dae435cbc0103b1d771573eac71cc2a0cd205bf)
