### ISSUE TITLE
Python: `easy_install`  '-Wstrict-prototypes' & numpi API

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#71]
Although it is already [tried to be removed](https://github.com/ornladios/ADIOS/blob/f74a74d1b4fddef19cf76eb17349af2ca4695db7/wrappers/numpy/conf/mpidistutils.py#L166), and `easy_install adios` on the latest PyPI release `1.9.1b9` still leads to a warning:

```bash
$ easy_install adios
Searching for adios
[...]
Best match: adios 1.9.1b9
Downloading [...]
Processing adios-1.9.1b9.tar.gz
Writing /tmp/easy_install-dmaVx3/adios-1.9.1b9/setup.cfg
Running adios-1.9.1b9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dmaVx3/adios-1.9.1b9/egg-dist-tmp-7lor2Q
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]

[...]
```

Also the old, *deprecated* numpy api is used:
```
In file included from /sw/rhea/python_numpy/1.9.2/python2.7.9_gnu4.8.2_acml5.3.0/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /sw/rhea/python_numpy/1.9.2/python2.7.9_gnu4.8.2_acml5.3.0/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /sw/rhea/python_numpy/1.9.2/python2.7.9_gnu4.8.2_acml5.3.0/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from adios.cpp:251:
/sw/rhea/python_numpy/1.9.2/python2.7.9_gnu4.8.2_acml5.3.0/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
zip_safe flag not set; analyzing archive contents...
```

**Comment by yyalli** [comment]
Regarding the numpy warning on using deprecated APIs, it looks like Cython is using the old numpy APIs and there is no way to avoid this warning at this moment (see [here](http://stackoverflow.com/questions/25789055/cython-numpy-warning-about-npy-no-deprecated-api-when-using-memoryview))

**Comment by ax3l** [comment]
huh, good to know the cython reason behind it. thank you!

**Comment by yyalli** [comment]
If the command line option '-Wstrict-prototypes' was used on building python, it cannot be override or removed. We can see by the following command: python-config --cflags

I have also found [this](https://svn.python.org/projects/python/trunk/README). It looks like '-Wstrict-prototypes' is a default option for GCC.

So, at this moment, I cannot remove those warnings.

**Comment by ax3l** [comment]
Thank you for looking into this. Yes, I think the problem is that CPython is compiled with it and for some reason it (cython?) takes over the c flags and compiles c++ code with it. Here is also a stackoverflow answer tracing it back into the `build_ext` suite: http://stackoverflow.com/questions/8106258/cc1plus-warning-command-line-option-wstrict-prototypes-is-valid-for-ada-c-o/8106847#8106847

Probably both warnings are not in our control right now.
