### ISSUE TITLE
--without-mpi not working

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#74]
To build simple serial tools, such as the no-mpi versions of the numpy wrappers, MPI is not required.
Unfurtunately, `configure --without-mpi` is not working.

**Comment by ax3l** [comment]
@pnorbert needed for simple packaging, distributing and CI of @yyalli 's numpy wrapper.

**Comment by ax3l** [comment]
In case you use docker, here is how to reproduce the problem with a default Ubuntu without MPI:
```bash
docker run -it ubuntu
apt-get update
apt-get install -y libmxml-dev wget unzip autoconf automake libtool

wget https://github.com/ornladios/ADIOS/archive/master.zip 
unzip master.zip
cd ADIOS-master

./autogen.sh
CFLAGS="-fPIC" ./configure --with-mxml=/usr --with-mxml=/usr --without-mpi
# configure: error: could not find mpi library for C
```

**Comment by pnorbert** [comment]
We never supported sequential-only build. I agree it could be practical to
implement --without-mpi

**Comment by pnorbert** [comment]
ADIOS now builds --without-mpi since commit 6c393e2665147

**Comment by ax3l** [comment]
@pnorbert thank you so much, that feature is wonderful! :sparkles:
