### ISSUE TITLE
Distribute mxml along with ADIOS, or make it optional

### ISSUE THREAD

**Issue by andrewcorrigan** [ornladios/ADIOS#8]
Is it possible to distribute and automatically build MXML with ADIOS?   I wouldn't make such a request about a large library like HDF5, but MXML is small and not that common either.   This would be one less step in getting ADIOS set up and installed.

Alternatively, could the XML interface to ADIOS please be made optional?  My code doesn't use the XML interface to ADIOS, so perhaps it is not necessary, and could be disabled at compile-time.

**Comment by wjlei1990** [comment]
I am an user on Titan, Rhea and EOS@ORNL. I experienced several times when mxml is not configured correctly in adios on ORNL machines. So I basically load the adios and mxml from the system modules but there are still times things didn't work. Just today, I am working on python APIs one EOS@ORNL, and when I import the adios, it told me it can't find `libmxml.so`.

I know from the software developer's point, mxml should be independently built but there are just times things get broken.

**Comment by pnorbert** [comment]
mxml is packaged into ADIOS since 1.10
