### ISSUE TITLE
1.10.0: autotools (configure) missing

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#84]
In the latest tag `1.10.0` the one forgot to run autotools so one can directly download and `./configure` it from https://github.com/ornladios/ADIOS/archive/v1.10.0.tar.gz (see [ADIOS->releases](https://github.com/ornladios/ADIOS/releases))

**Comment by pnorbert** [comment]
The autopacked v.*.tar.gz were never intended to be release packages. It's
just a tar of the source code. One needs to run ./autogen.sh and have the
autotools on the system installed to generate the configure script. One
should have used the official release page to download adios-1.10.0.tar.gz

BTW, for the next tag, the https://github.com/ornladios/ADIOS/releases page
will be modified to have the official release package included.

**Comment by ax3l** [comment]
Yes I guess you prefer the NCSS server as download, but github automatically creates a convenient `project/archive/vX.Y.Z.tar.gz` download link for each package (and robert reported user.ncss might be replaced/unplugged in https://github.com/LLNL/spack/pull/1302)

In case you want to have the same convencience for auto-generated links on github, just create a branch with the changes you would do for your "normal" `.tar.gz` release anyway, do the changes such as running `./autogen.sh` to it and tag the result. then just `git push --tags` that tag.

**Comment by pnorbert** [comment]
That's not only what we are doing. After make dist, we remove some files
and add other files to the tar.gz. We have to rethink how to create a
branch just for the releases. It's not a convenience for us, even if it
works fine for other projects.

**Comment by ax3l** [comment]
I see, thanks! just an idea to bring the auto-created archives for tags on github a bit closer to the final package :)

**Comment by pnorbert** [comment]
Yes, NCCS also wants us to move the releases to github, so we are heading
towards it.

**Comment by olesenm** [comment]
Is configure or cmake the preferred method in the (near) future? Is cmake slated for use and configure to be deprecated, vice versa or a bit of both? I don't really mind either way - it's just nice to know.

**Comment by pnorbert** [comment]
Both are going to be supported for the lifetime of this adios repository.
We are sort of stuck with them. Autoconf works fine to build modules on the
supercomputers and our transition plans to cmake slowly died away, still it
is supported too at every release. The cmake build can lag behind between
releases. New additions are always going into the automake build simply
because of my preference.

**Comment by olesenm** [comment]
Thanks Norbert for the info. Configure is fine and is probably quite good to manage with the few dependencies that ADIOS has (excluding all of the dependencies like mxml and zfp that we no longer need to worry about!).
If you have the idea of issuing a 1.10.1 patch release, it would great if zfp could be added then too. It looks like an interesting technology.

**Comment by pnorbert** [comment]
1.11 is coming shortly. ZFP + time aggregation included.
