### ISSUE TITLE
Java wrapper build error

### ISSUE THREAD

**Issue by SmithRWORNL** [ornladios/ADIOS#87]
I'm trying to build the Java wrapper in wrappers/java but am getting an error when I run make.
```

/usr/bin/ld: /usr/local/lib/libadios.a(libadios_a-adios.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libadios.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libAdiosJava.so] Error 1
make[1]: *** [CMakeFiles/AdiosJava.dir/all] Error 2
make: *** [all] Error 2
```

I downloaded ADIOS from the OLCF site and built it as in the instruction manual. Then I created a build folder in wrappers/java, ran "cmake .." and "make". I've also tried running "../configure --with-pic" and setting the CXXFLAGS environmental variable to include -fPIC when building ADIOS, but I got the same error. Running mpiCC -v shows me that it's configured with the --enable-shared flag, so that doesn't appear to be the problem either.

What could be the cause of this issue?

**Comment by yyalli** [comment]
It looks like --with-pic and --enable-shared are not working properly. Can you configure "-fPIC" option directly as follows?
$ configure ... CFLAGS="-fPIC"

**Comment by SmithRWORNL** [comment]
I still got the same error message.

Note that when I build ADIOS itself, I see that in the General Compile FLAGS section, it was listed as CFLAGS = -fPIC (where previously it had been CFLAGS= -g -O2 -fPIC), so it seems at least the ADIOS build is getting the configuration.

**Comment by yyalli** [comment]
Does your Adios build have any dependent libraries? I don't remember for sure but it may require that depending libraries also needs to be built with "-fPIC".

-- 
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

**Comment by SmithRWORNL** [comment]
Not that I know of. I just went through the "Quick installation with Automake" and "Support for Java" sections in the manual. Would either of those require another library be rebuilt with the -fPIC flag?

**Comment by yyalli** [comment]
No. If you just followed the manual, it should be fine.

Let's make sure libadios.a is built properly. Can you do the following?

$ objdump -r /usr/local/lib/libadios.a | grep "RELOCATION RECORDS FOR \[.text\]" -B2 -A2

and check if you can see something like at the beginning:
libadios_a-adios.o:     file format elf64-x86-64

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE 
0000000000000055 R_X86_64_PC32     .data+0x00000000000002bc

I found this solution here: 
http://stackoverflow.com/questions/3507296/is-there-a-way-to-determine-that-a-a-or-so-library-has-been-compiled-as-positi 

And, I tested working on my machine too.

Thanks,
Jong

**Comment by SmithRWORNL** [comment]
I got a large number of relocation records. The only one that mentioned libadios_a-adios.o was:

libadios_a-adios.o:     file format elf64-x86-64

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE 
0000000000000005 R_X86_64_PC32     globals_adios_set_application_id-0x0000000000000004

I also found this reference to the .rodata.str1.1 mentioned in my error message.

libcoreonce_a-util.o:     file format elf64-x86-64

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE 
000000000000006d R_X86_64_32       .rodata.str1.1

**Comment by pnorbert** [comment]
Did you rebuild adios after a make clean? It looks like
libcoreonce_a-util.o was not compiled with the -fPIC flag.

**Comment by SmithRWORNL** [comment]
Ah, it was just that I needed to do a make clean to clear the old build. I was able to build the Java example successfully after that.

Thank you for the help!

**Comment by physixfan** [comment]
I strongly suggest you add "remember to make clean before rebuilding with -fPIC" in the manual. I have wasted 2 hours on this issue.
