### ISSUE TITLE
Apparently no support for --enable-shared

### ISSUE THREAD

**Issue by davidozog** [ornladios/ADIOS#93]
Is it possible to create a shared/dynamic library of ADIOS?  I'm using a separate library that requires support for dlopen() and I'm trying to feed ADIOS through it.  The --help menu for ADIOS's configure script suggests that --enable-shared should create dynamic libraries.  Is that not the case?  If not, is there any particular reason ADIOS might only work as a static library?  Thanks.

**Comment by pnorbert** [comment]
Hi, the enable-shared option does not work but there is a manual way to
create a shared library. Add -fPIC to both CFLAGS and LDFLAGS and build
adios static libraries. Then you can create a shared libadios.so from the
libadios.a manually

gcc -shared -o libadios.so -Wl,--whole-archive -ladios -Wl,--no-whole-archive

**Comment by davidozog** [comment]
Thanks very much, that could be pretty handy in general.
