### ISSUE TITLE
No obvious way for a program to check available transform methods

### ISSUE THREAD

**Issue by olesenm** [ornladios/ADIOS#98]
Similar to what is possible with `adios_list_methods` I would like to check which transform methods are available to provide my own user feedback (or abort) as needed.

As pseudo-code

    const List<adiosTransform>& available = adios_implemented_transforms(); 
    for (adiosTransform::const_iterator iter = available.cbegin(); iter != available.cend();++iter)
    {
        hashset.add(iter.xmlName());
    }

    if (!hashset.exists("someTransform"))  ...

But most of the headers are tagged as internal, so it's not easily possible to write this myself, unless I also copy across the internal headers into my include directory etc, but this isn't the nicest way of doing things.

**Comment by pnorbert** [comment]
commit 729956d0

#include "adios_transform_methods.h"

ADIOS_IMPLEMENTED_TRANSFORMS * t = adios_implemented_transforms();
if (t) {
    for (i=0; i<t->ntransforms; i++)
    {
        printf("    \"%s\"\t: %s\n",  t->name[i], t->description[i]);
    }
    adios_implemented_transforms_free(t);
}

**Comment by olesenm** [comment]
Thanks - that was really fast! I'm travelling and can't check it immediately, but code looks like what I need.

**Comment by pnorbert** [comment]
Changed API to adios_available_transforms(), and added similar functions:
   adios.h: adios_available_write_methods()
   adios_read.h: adios_available_read_methods() 
   adios_query.h: adios_available_query_methods()

        printf ("Available data transformation methods (in XML transform tags in <var> elements):\n");
        ADIOS_AVAILABLE_TRANSFORMS * t = adios_available_transforms();
        if (t) {
            for (i=0; i<t->ntransforms; i++)
            {
                printf("    \"%s\"\t: %s\n",  t->name[i], t->description[i]);
            }
            adios_available_transforms_free(t);
        }

**Comment by pnorbert** [comment]
Okay, one more try, let's make them even more consistent:

ADIOS_AVAILABLE_TRANSFORM_METHODS * t = adios_available_transform_methods();
if (t) {
    for (i=0; i<t->ntransforms; i++)
    {
        printf("    \"%s\"\t: %s\n",  t->name[i], t->description[i]);
    }
    adios_available_transform_methods_free(t);
}

**Comment by olesenm** [comment]
Minor bug due to initialization

[0001-BUG-segfault-when-querying-list-of-available-transfo.patch.txt](https://github.com/ornladios/ADIOS/files/603304/0001-BUG-segfault-when-querying-list-of-available-transfo.patch.txt)
